version: '3'

services:
  sherlock:
    build:
      context: .
    links:
      - etcd:etcd
      - redis:redis
      - memcached:memcached
    volumes:
      - .:/sherlock:Z
    entrypoint: bash -c 'pip install -e . && pytest --cov-report term --cov-report xml tests/'
    stdin_open: true
    tty: true
  etcd:
    image: quay.io/coreos/etcd
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
    ports:
      - 2379:2379
      - 4001:4001
  redis:
    image: redis
  memcached:
    image: memcached
