name: CI/CD

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    name: Test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        py:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    env:
      REDIS_HOST: 127.0.0.1
      ETCD_HOST: 127.0.0.1
      MEMCACHED_HOST: 127.0.0.1

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Install Dev requirements
        run: pip install -r requirements-dev.txt

      - name: Install `libmemcached-dev`
        run: sudo apt-get install -y libmemcached-dev

      - name: Run tests
        run: tox

      - uses: codecov/codecov-action@v3
